name: Update Homerun Data

on:
  schedule:
    - cron: "0 3 * * *"  # every day at 3am UTC
  workflow_dispatch:     # allows manual run from GitHub Actions tab

permissions:
  contents: write 

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests mlb-statsapi

      - name: Run update script
        run: python generate_homerun_data.py

      - name: Commit and push updated data
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add data/homeruns.csv
          git commit -m "Update homerun data [automated]" || echo "No changes to commit"
          git push
