name: Update Homerun Data

on:
  schedule:
    - cron: "0 3 * * *"  # Run daily at 3am UTC
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: write         # ✅ Required to allow git push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests mlb-statsapi

      - name: Run update script
        run: python scripts/generate_homerun_data.py

      - name: List contents of data folder
        run: ls -la data

      - name: Commit and push updated data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          git commit -m "Update homerun data [automated]" || echo "No changes to commit"
          git push
